In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('/Users/adi/Desktop/TA_Adi_V2/QE Statistik V2/tingkat_keparahan/dataset_keparahan.csv')
df

,No Document,title,Description,Mati,Luka,Kerugian Barang,Kerugian Uang,Pemerkosaan,Keparahan
0,0,Maling Motor Parlente di Pasuruan Gondol Motor...,\-\n\nMaling perlente beraksi di sebuah klinik...,0,0,1,0,0,1.0
1,1,2 Komplotan Maling Motor Asal Tangerang dan Le...,\-\n\nPolsek Neglasari meringkus dua komplotan...,0,0,2,0,0,1.0
2,2,Pria di Dairi Nekat Habisi Oppungnya demi Perh...,"\-\n\nSeorang pria di Kabupaten Dairi, bernama...",1,0,1,1,0,3.0
3,3,"Korban Curanmor Silakan Merapat, Ada 7 Mobil-4...",\-\n\nPolres Bogor menyita 7 mobil dan 48 moto...,0,0,7,0,0,3.0
4,4,"Kepergok Curi Motor Mahasiswa USU, 2 Pria Ini ...",\-\n\n2 pelaku pencuri sepeda motor milik maha...,0,1,2,0,0,3.0
...,...,...,...,...,...,...,...,...,...
1200,1202,Maling Spesialis Rumah Kosong Diciduk di Bantul,\-\n\nPolisi menciduk pria inisial FA (28) kar...,0,0,3,0,0,2.0
1201,1203,Ini TKP Penemuan Mayat Gadis ABG Korban Pembun...,"\-\n\nWarga Desa Kaliputih, Kecamatan Alian, K...",1,0,1,0,0,3.0
1202,1204,Tetangga Curi Duit Wakil Ketua DPRD Bone Rp 64...,\-\n\nPolisi menetapkan 4 orang tersangka dala...,0,0,0,640000000,0,3.0
1203,1205,CIMB Niaga Buka Suara Terkait Perampokan Bank ...,\-\n\nPria berinisial BS (43) ditangkap dan di...,0,0,0,0,0,1.0
1204,1206,Kisah Pendakwah Gadungan Arab Saudi yang Siksa...,\-\n\nNama Fayhan Al-Ghamdi memenuhi headline ...,1,0,0,0,0,3.0

In [16]:
df.isna()

,No Document,title,Description,Mati,Luka,Kerugian Barang,Kerugian Uang,Pemerkosaan,Keparahan
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
1200,False,False,False,False,False,False,False,False,False
1201,False,False,False,False,False,False,False,False,False
1202,False,False,False,False,False,False,False,False,False
1203,False,False,False,False,False,False,False,False,False
1204,False,False,False,False,False,False,False,False,False

In [12]:
df.dropna(subset=["Keparahan"], axis=0)

,No Document,title,Description,Mati,Luka,Kerugian Barang,Kerugian Uang,Pemerkosaan,Keparahan
0,0,Maling Motor Parlente di Pasuruan Gondol Motor...,\-\n\nMaling perlente beraksi di sebuah klinik...,0,0,1,0,0,1.0
1,1,2 Komplotan Maling Motor Asal Tangerang dan Le...,\-\n\nPolsek Neglasari meringkus dua komplotan...,0,0,2,0,0,1.0
2,2,Pria di Dairi Nekat Habisi Oppungnya demi Perh...,"\-\n\nSeorang pria di Kabupaten Dairi, bernama...",1,0,1,1,0,3.0
3,3,"Korban Curanmor Silakan Merapat, Ada 7 Mobil-4...",\-\n\nPolres Bogor menyita 7 mobil dan 48 moto...,0,0,7,0,0,3.0
4,4,"Kepergok Curi Motor Mahasiswa USU, 2 Pria Ini ...",\-\n\n2 pelaku pencuri sepeda motor milik maha...,0,1,2,0,0,3.0
...,...,...,...,...,...,...,...,...,...
1200,1202,Maling Spesialis Rumah Kosong Diciduk di Bantul,\-\n\nPolisi menciduk pria inisial FA (28) kar...,0,0,3,0,0,2.0
1201,1203,Ini TKP Penemuan Mayat Gadis ABG Korban Pembun...,"\-\n\nWarga Desa Kaliputih, Kecamatan Alian, K...",1,0,1,0,0,3.0
1202,1204,Tetangga Curi Duit Wakil Ketua DPRD Bone Rp 64...,\-\n\nPolisi menetapkan 4 orang tersangka dala...,0,0,0,640000000,0,3.0
1203,1205,CIMB Niaga Buka Suara Terkait Perampokan Bank ...,\-\n\nPria berinisial BS (43) ditangkap dan di...,0,0,0,0,0,1.0
1204,1206,Kisah Pendakwah Gadungan Arab Saudi yang Siksa...,\-\n\nNama Fayhan Al-Ghamdi memenuhi headline ...,1,0,0,0,0,3.0

In [13]:
df.to_csv('dataset_keparahan_filter.csv')